Enhance readme documentation
quarkiverse/quarkus-jnosql pull request #73
Opened 2024-01-09 04:30 UTC by otaviojava

# Changes

- Update readme file

2024-01-27 08:19 UTC, otaviojava commented
@amoscatelli and @dearrudam could you review this, please?

2024-01-27 20:30 UTC, dearrudam requested changes
@otaviojava, thank you so much for this documentation enhancement! I've suggested some changes also! See ya!!!

2024-01-27 20:30 UTC, dearrudam commented on README.md
> +For specific configuration details, please refer to the [AranboDB JNoSQL driver](https://github.com/eclipse/jnosql-databases#arangodb).
```suggestion
For specific configuration details, please refer to the [ArangoDB JNoSQL driver](https://github.com/eclipse/jnosql-databases#arangodb).
```

2024-01-27 20:30 UTC, dearrudam commented on README.md
> +For specific configuration details, please refer to the [AranboDB JNoSQL driver](https://github.com/eclipse/jnosql-databases#arangodb).
```suggestion
For specific configuration details, please refer to the [ArangoDB JNoSQL driver](https://github.com/eclipse/jnosql-databases#arangodb).
```

2024-01-27 20:30 UTC, dearrudam commented on README.md
> +- [dearrudam](https://github.com/dearrudam) 💻 🚧
```suggestion
- [dearrudam](https://github.com/dearrudam) 💻 🚧
- [otaviojava](https://github.com/otaviojava) 💻 🚧
```

2024-01-28 19:17 UTC, dearrudam approved these changes

2024-01-30 15:52 UTC, otaviojava commented
@gastaldi could you review/merge this one?

2024-01-30 15:56 UTC, gastaldi commented on README.md
> +This documentation provides instructions on how to integrate JNoSQL, an implementation of [Jakarta NoSQL](https://jakarta.ee/specifications/nosql/), into a Quarkus project using the Quarkus JNoSQL Ex
Why removing the link to https://www.jnosql.org/?

2024-01-30 15:59 UTC, gastaldi commented
Although it looks okay, I'd prefer to have this information in https://github.com/quarkiverse/quarkus-jnosql/blob/master/docs/modules/ROOT/pages/index.adoc instead (which is published in https://docs.quarkiverse.io/quarkus-jnosql/dev/index.html consequently).

2024-01-30 16:00 UTC, otaviojava commented
> https://docs.quarkiverse.io/quarkus-jnosql/dev/index.html

I will update this one as well. Thank you.

2024-01-30 16:01 UTC, gastaldi commented on README.md
> +- [otaviojava](https://github.com/otaviojava) 💻 🚧
This section should be only changed by the @all-contributors bot (maintainers should trigger it by commenting something like `@all-contributors add @otaviojava for code and maintenance`

2024-01-31 05:48 UTC, otaviojava commented
> Although it looks okay, I'd prefer to have this information in https://github.com/quarkiverse/quarkus-jnosql/blob/master/docs/modules/ROOT/pages/index.adoc instead (which is published in https://docs.quarkiverse.io/quarkus-jnosql/dev/index.html consequently).

I updated both; I will include more documentation at this index as next step.

2024-01-31 05:59 UTC, dearrudam approved these changes

2024-02-01 09:38 UTC, merged

2024-02-01 09:38 UTC, amoscatelli commented
LGTM thank you all